spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: driver-service
              uri: lb://driver-service
              predicates:
                - Path=/api/driver/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
                - Path=/api/person/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
  instance:
    prefer-ip-address: true
